[kijanikiosk_api]
api ansible_host=10.32.18.69

[kijanikiosk_payments]
payments ansible_host=10.32.18.210

[kijanikiosk_logs]
logs ansible_host=10.32.18.211

[kijanikiosk:children]
kijanikiosk_api
kijanikiosk_payments
kijanikiosk_logs

[kijanikiosk:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/medico/.ssh/id_rsa
ansible_python_interpreter=/usr/bin/python3
